/*
 * SPDX-FileCopyrightText: 2026 lvgl_pinyin_ime contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * 9-key (T9) front end: turn a digit buffer such as "94" into the pinyin
 * strings it can stand for ("xi", "yi", "zi"), so the engine can then produce
 * Chinese candidates for the chosen spelling.
 *
 * The syllable -> digit table is generated by tools/gen_t9_table.py from the
 * same word list the engine dictionary is built from, so a segmentation can
 * never produce a spelling the engine does not know.
 */

#include "ime_t9.h"

#include "generated/ime_t9_syllables.h"
#include "ime_trie.h"

#include <stdio.h>
#include <string.h>

#define T9_MAX_RESULTS IME_T9_MAX_PINYIN
#define T9_MAX_SYLLABLE 6

static char s_digits[IME_T9_MAX_DIGITS + 1];
static size_t s_digits_len;

static char s_results[T9_MAX_RESULTS][IME_T9_MAX_PINYIN_LEN + 1];
static size_t s_result_count;
static size_t s_selected;

static char s_scratch[IME_T9_MAX_PINYIN_LEN + 1];

static void emit_result(const char *text)
{
    if (s_result_count >= T9_MAX_RESULTS || text[0] == '\0') {
        return;
    }
    snprintf(s_results[s_result_count], sizeof(s_results[0]), "%s", text);
    s_result_count++;
}

/*
 * Complete segmentations only: every syllable must be a whole syllable of the
 * table, and the whole buffer must be consumed.
 *
 * The table holds only complete syllables, so comparing a syllable over its own
 * full length is the check. Comparing a *shorter* slice of the buffer against it
 * is what produced the invented spelling "ea" for "32": the comparison matched a
 * longer syllable's digits that merely started with the buffer.
 *
 * A single-letter syllable (the word list really does carry 锕 a, 唔 n, 呣 m) is
 * only allowed when it is the entire buffer. Chaining them is what produced the
 * useless suggestion "e'a" for "32", purely because 'e' sits on the 3 key and 'a'
 * on the 2 key: technically a valid key reading, but not a word anyone types.
 */
static void seg(size_t pos, const char *acc)
{
    if (s_result_count >= T9_MAX_RESULTS) {
        return;
    }
    if (pos == s_digits_len) {
        emit_result(acc);
        return;
    }

    for (size_t i = 0; i < IME_T9_SYLLABLE_COUNT && s_result_count < T9_MAX_RESULTS; i++) {
        const char *digits = ime_t9_syllables[i].digits;
        size_t dlen = strlen(digits);
        if (dlen > s_digits_len - pos) {
            continue;
        }
        if (strncmp(s_digits + pos, digits, dlen) != 0) {
            continue;
        }
        if (dlen == 1 && s_digits_len > 1) {
            continue;
        }

        size_t acc_len = strlen(acc);
        size_t syl_len = strlen(ime_t9_syllables[i].syllable);
        if (acc_len + syl_len + 2 > IME_T9_MAX_PINYIN_LEN) {
            continue;
        }

        char next[IME_T9_MAX_PINYIN_LEN + 2];
        memcpy(next, acc, acc_len);
        if (acc_len > 0) {
            next[acc_len++] = '\'';
        }
        memcpy(next + acc_len, ime_t9_syllables[i].syllable, syl_len + 1);

        seg(pos + dlen, next);
    }
}

/* Fallback for a prefix that has no complete spelling: propose the syllables
 * the remaining digits could still grow into, marked with a trailing '\''.
 * The engine cannot decode those, so the UI shows them as a hint only. The
 * candidate list comes from ime_trie, which also orders it shortest first. */
static void seg_partial(size_t pos, const char *acc)
{
    ime_trie_match_t matches[IME_T9_PARTIAL_MAX];
    ime_trie_init();
    size_t count = ime_trie_children(s_digits + pos, matches, IME_T9_PARTIAL_MAX);

    for (size_t i = 0; i < count && s_result_count < IME_T9_PARTIAL_MAX; i++) {
        if (matches[i].is_exact) {
            continue; /* an exact spelling is not a partial suggestion */
        }

        size_t acc_len = strlen(acc);
        size_t syl_len = strlen(matches[i].syllable);
        if (acc_len + syl_len + 2 > IME_T9_MAX_PINYIN_LEN) {
            continue;
        }

        char next[IME_T9_MAX_PINYIN_LEN + 2];
        memcpy(next, acc, acc_len);
        if (acc_len > 0) {
            next[acc_len++] = '\'';
        }
        memcpy(next + acc_len, matches[i].syllable, syl_len + 1);

        size_t next_len = strlen(next);
        next[next_len] = '\'';
        next[next_len + 1] = '\0';

        emit_result(next);
    }
}

static bool is_partial(size_t index)
{
    size_t len = strlen(s_results[index]);
    return len > 0 && s_results[index][len - 1] == '\'';
}

static void drop_partials(void)
{
    bool complete = false;
    for (size_t i = 0; i < s_result_count && !complete; i++) {
        complete = !is_partial(i);
    }
    if (!complete) {
        return;
    }

    size_t out = 0;
    for (size_t i = 0; i < s_result_count; i++) {
        if (is_partial(i)) {
            continue;
        }
        if (out != i) {
            memcpy(s_results[out], s_results[i], sizeof(s_results[0]));
        }
        out++;
    }
    s_result_count = out;
}

static void rebuild(void)
{
    s_result_count = 0;
    s_selected = 0;
    s_scratch[0] = '\0';

    if (s_digits_len == 0) {
        return;
    }
    seg(0, "");
    if (s_result_count == 0) {
        seg_partial(0, "");
        return;
    }
    drop_partials();
}

void ime_t9_init(void)
{
    ime_t9_reset();
}

void ime_t9_deinit(void)
{
    ime_t9_reset();
}

void ime_t9_reset(void)
{
    s_digits[0] = '\0';
    s_digits_len = 0;
    s_result_count = 0;
    s_selected = 0;
}

bool ime_t9_push_digit(char digit)
{
    if (digit < '2' || digit > '9' || s_digits_len >= IME_T9_MAX_DIGITS) {
        return false;
    }
    s_digits[s_digits_len++] = digit;
    s_digits[s_digits_len] = '\0';
    rebuild();

    /* A digit is only accepted when the buffer can still be read as pinyin. */
    if (s_result_count == 0) {
        s_digits_len--;
        s_digits[s_digits_len] = '\0';
        rebuild();
        return false;
    }
    return true;
}

void ime_t9_backspace(void)
{
    if (s_digits_len == 0) {
        return;
    }
    s_digits_len--;
    s_digits[s_digits_len] = '\0';
    rebuild();
}

size_t ime_t9_len(void)
{
    return s_digits_len;
}

const char *ime_t9_digits(void)
{
    return s_digits;
}

size_t ime_t9_count(void)
{
    return s_result_count;
}

const char *ime_t9_pinyin(size_t index)
{
    if (index >= s_result_count) {
        return NULL;
    }
    return s_results[index];
}

bool ime_t9_is_valid(const char *pinyin)
{
    if (pinyin == NULL || pinyin[0] == '\0') {
        return false;
    }

    size_t len = strlen(pinyin);
    size_t start = 0;

    for (size_t i = 0; i <= len; i++) {
        bool at_separator = (i == len) || (pinyin[i] == '\'');
        if (!at_separator) {
            continue;
        }

        size_t syl_len = i - start;
        /* A trailing separator marks a partial suggestion: valid so far. */
        if (syl_len == 0) {
            if (i == len && start > 0) {
                return true;
            }
            return false;
        }

        bool known = false;
        for (size_t s = 0; s < IME_T9_SYLLABLE_COUNT; s++) {
            const char *syl = ime_t9_syllables[s].syllable;
            if (strlen(syl) == syl_len && strncmp(syl, pinyin + start, syl_len) == 0) {
                known = true;
                break;
            }
        }
        if (!known) {
            return false;
        }

        start = i + 1;
    }

    return true;
}

size_t ime_t9_selected_index(void)
{
    return s_selected;
}

const char *ime_t9_selected_pinyin(void)
{
    if (s_result_count == 0) {
        return "";
    }
    return s_results[s_selected < s_result_count ? s_selected : 0];
}

bool ime_t9_select(size_t index)
{
    if (index >= s_result_count) {
        return false;
    }
    s_selected = index;
    return true;
}

/* The scratch buffer is reserved for the caller that wants to build a display
 * string out of the selected spelling; exposed for symmetry with the API in
 * ime_session. */
char *ime_t9_scratch(void)
{
    return s_scratch;
}
