#!/usr/bin/env python3
"""Generate the pinyin syllable table used by the 9-key input method.

Source of truth: the raw word list shipped with libgooglepinyin
(data/dict/rawdict_utf16_65105_freq.txt). Every line is
    <hanzi> <freq> <n> <syllable> [<syllable> ...]
in UTF-16LE, so the distinct syllables of column 4 onward are exactly the
spellings the engine accepts - the 9-key segmentation can therefore never
produce a spelling the engine does not know.

Output: src/generated/ime_t9_syllables.h - a compact table of
  syllable string -> T9 digit string
sorted by digit string so the 9-key selector can walk it linearly.

Usage:
    python tools/gen_t9_table.py [--input data/dict/rawdict_utf16_65105_freq.txt]
                                 [--output src/generated/ime_t9_syllables.h]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

T9_MAP = {
    "a": "2", "b": "2", "c": "2",
    "d": "3", "e": "3", "f": "3",
    "g": "4", "h": "4", "i": "4",
    "j": "5", "k": "5", "l": "5",
    "m": "6", "n": "6", "o": "6",
    "p": "7", "q": "7", "r": "7", "s": "7",
    "t": "8", "u": "8", "v": "8",
    "w": "9", "x": "9", "y": "9", "z": "9",
}

MAX_DIGITS = 5


def read_syllables(path: pathlib.Path) -> list[str]:
    raw = path.read_bytes()
    text = raw.decode("utf-16-le", errors="replace")
    if text.startswith("\ufeff"):
        text = text[1:]

    out: set[str] = set()
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        for token in parts[3:]:
            token = token.strip().lower()
            if token and all(c in T9_MAP for c in token):
                out.add(token)
    return sorted(out)


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=str(root / "data" / "dict" / "rawdict_utf16_65105_freq.txt"))
    ap.add_argument("--output", default=str(root / "src" / "generated" / "ime_t9_syllables.h"))
    args = ap.parse_args()

    src = pathlib.Path(args.input)
    if not src.exists():
        print(f"input not found: {src}", file=sys.stderr)
        return 1

    syllables = sorted(set(read_syllables(src)))
    if not syllables:
        print("no syllables parsed", file=sys.stderr)
        return 1

    entries = []
    for syl in syllables:
        digit = "".join(T9_MAP[c] for c in syl)
        if len(digit) > MAX_DIGITS:
            continue
        entries.append((digit, syl))
    entries.sort(key=lambda e: (e[0], e[1]))

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "/*",
        " * SPDX-FileCopyrightText: 2026 lvgl_pinyin_ime contributors",
        " * SPDX-License-Identifier: Apache-2.0",
        " *",
        " * Generated by tools/gen_t9_table.py - do not edit by hand.",
        f" * Source: {pathlib.Path(args.input).name} ({len(entries)} syllables).",
        " */",
        "",
        "#pragma once",
        "",
        "typedef struct {",
        "    const char *digits;  /* T9 key sequence, '2'..'9' */",
        "    const char *syllable;/* full pinyin of the key sequence */",
        "} ime_t9_syllable_t;",
        "",
        f"#define IME_T9_SYLLABLE_COUNT {len(entries)}",
        f"#define IME_T9_SYLLABLE_MAX_DIGITS {MAX_DIGITS}",
        "",
        "static const ime_t9_syllable_t ime_t9_syllables[IME_T9_SYLLABLE_COUNT] = {",
    ]
    for digit, syl in entries:
        lines.append(f'    {{"{digit}", "{syl}"}},')
    lines.append("};")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(entries)} syllables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
