/*
 * SPDX-FileCopyrightText: 2026 lvgl_pinyin_ime contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * IME font loading.
 *
 * Two sources, selected by CONFIG_LV_PINYIN_IME_FONT_SRC:
 *
 *   EMBEDDED (default)  the fonts generated by tools/gen_font.py as C arrays and
 *                       compiled into the application. Nothing to flash, no file
 *                       system involved, so this works on a fresh board.
 *   PARTITION           the fonts generated as LVGL binary fonts and flashed to
 *                       the "font" partition, loaded through LVGL's memory file
 *                       system (needs CONFIG_LV_USE_FS_MEMFS).
 *
 * Loading is best effort: when no font is available the IME falls back to
 * LV_FONT_DEFAULT and CJK text draws as boxes, but the keyboard keeps working.
 */

#pragma once

#include <stdbool.h>

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Load the fonts from the configured source.
 *
 * Safe to call more than once, and safe to fail.
 *
 * @return true when at least the big font was loaded
 */
bool ime_font_init(void);

/** Destroy the loaded fonts. */
void ime_font_deinit(void);

/** Big font (candidates and committed text), or NULL when unavailable. */
lv_font_t *ime_font_big(void);

/** Small font (key captions and the pinyin chip), or NULL. */
lv_font_t *ime_font_small(void);

#ifdef __cplusplus
}
#endif
