/*
 * SPDX-FileCopyrightText: 2026 lvgl_pinyin_ime contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Loads the IME fonts generated by tools/gen_font.py.
 *
 * Default (CONFIG_LV_PINYIN_IME_FONT_SRC_EMBEDDED): the generated C files are
 * compiled in and referenced directly, so there is no file, no partition and no
 * file system involved. This is what makes a freshly flashed board show the
 * keyboard with real glyphs.
 *
 * Alternative (PARTITION): the LVGL binary fonts are concatenated big-first into
 * the "font" partition and loaded through lv_binfont_create_from_buffer(), which
 * needs LV_USE_FS_MEMFS. The partition has no directory entry layout, so the size
 * of the first font is recovered by walking its [u32 length][4 byte label] table
 * headers: the big font ends where the small font's "head" table begins.
 */

#include "ime_font.h"

#include <stdio.h>
#include <string.h>

#include "../core/ime_log.h"
#include "ime_dict_vfs.h"

static const char *TAG = "ime_font";

static lv_font_t *s_big;
static lv_font_t *s_small;
static bool s_prepared;

/* ------------------------------------------------------------------ embedded */

/*
 * Which source to use, decided once so every block below agrees.
 *
 * EMBEDDED: the generated C arrays. Selected by Kconfig on the device, or by
 *   -DIME_FONT_EMBEDDED on a host build (the render harness).
 * PARTITION: the flashed LVGL binary font. Needs esp_partition, so it is only
 *   ever compiled for ESP_PLATFORM.
 */
#if defined(CONFIG_LV_PINYIN_IME_FONT_SRC_EMBEDDED) || defined(IME_FONT_EMBEDDED) || \
    !defined(ESP_PLATFORM)
#define IME_FONT_USE_EMBEDDED 1
#else
#define IME_FONT_USE_EMBEDDED 0
#endif

#if IME_FONT_USE_EMBEDDED
/*
 * lv_font_conv (all versions up to at least 1.5.2) emits only the compact
 * glyph descriptor: `{.bitmap_index, .adv_w, .box_w, .box_h, .ofs_x, .ofs_y}`,
 * which is lv_font_fmt_txt_glyph_dsc_t with LV_FONT_FMT_TXT_LARGE == 0 (8 bytes:
 * bitmap_index is a 20 bit field). With the large format enabled the struct is
 * 12 bytes, so LVGL would walk glyph_dsc[] at the wrong stride and every glyph
 * would come out empty - the keyboard draws no text at all, which is far harder
 * to diagnose than a missing glyph box.
 *
 * Enabling it is the tempting reaction to "Too large font or glyphs in ...",
 * but for a lv_font_conv font that message means the glyph bitmap outgrew the
 * 20 bit offset field: lower --big-bpp or shrink the charset instead.
 * tools/gen_font.py refuses to emit a font whose bitmap does not fit.
 */
#if defined(LV_FONT_FMT_TXT_LARGE) && LV_FONT_FMT_TXT_LARGE != 0
#error "CONFIG_LV_FONT_FMT_TXT_LARGE must be OFF with a lv_font_conv generated font: the generator writes the compact 8 byte glyph descriptor, while the large format makes LVGL read 12 byte entries and draw no text at all. Turn it off and regenerate a smaller font instead (tools/gen_font.py checks the 1 MB bitmap limit)."
#endif

/* Generated by tools/gen_font.py --format c; each file defines an lv_font_t
 * named after the file. */
extern const lv_font_t lv_font_ime_20;
extern const lv_font_t lv_font_ime_16;
#endif

/* ------------------------------------------------------------------ partition */

#if !IME_FONT_USE_EMBEDDED
#if !defined(LV_USE_FS_MEMFS) || LV_USE_FS_MEMFS == 0
#error "the font partition is loaded with lv_binfont_create_from_buffer: enable CONFIG_LV_USE_FS_MEMFS, or switch CONFIG_LV_PINYIN_IME_FONT_SRC to EMBEDDED"
#endif

/** Where the font partition is exposed through the component's own VFS. */
#define IME_FONT_MOUNT_POINT "/ime"

/**
 * Size in bytes of the font image that starts at @p image.
 *
 * Walks the table headers until the next "head" table, which belongs to the
 * following font.
 */
static size_t first_font_size(const uint8_t *image, size_t limit)
{
    if (image == NULL || limit < 8) {
        return 0;
    }

    size_t offset = 0;
    bool saw_head = false;
    while (offset + 8 <= limit) {
        uint32_t table_len;
        memcpy(&table_len, image + offset, sizeof(table_len));
        const char *label = (const char *)(image + offset + 4);

        if (memcmp(label, "head", 4) == 0) {
            if (saw_head) {
                break; /* the second font starts here */
            }
            saw_head = true;
        }

        if (table_len == 0 || table_len > limit - offset) {
            break;
        }
        offset += table_len;
    }
    return saw_head ? offset : 0;
}
#endif /* !IME_FONT_USE_EMBEDDED */

/* --------------------------------------------------------------------- public */

lv_font_t *ime_font_big(void)
{
    return s_big;
}

lv_font_t *ime_font_small(void)
{
    return s_small;
}

bool ime_font_init(void)
{
    if (s_prepared) {
        return true;
    }

#if IME_FONT_USE_EMBEDDED
    /* Checked at compile time instead: the arrays are always present when the
     * generated sources are part of the build. */
    s_big = (lv_font_t *)&lv_font_ime_20;
    s_small = (lv_font_t *)&lv_font_ime_16;
    IME_LOGI(TAG, "embedded fonts: line heights %d (big) and %d (small)",
             (int)lv_font_ime_20.line_height, (int)lv_font_ime_16.line_height);
#else
#if defined(CONFIG_LV_PINYIN_IME_FONT_PARTITION)
    const char *label = CONFIG_LV_PINYIN_IME_FONT_PARTITION;
#else
    const char *label = "font";
#endif
    size_t partition_size = 0;
    ime_vfs_mount_t *mount = ime_vfs_mount_partition(label, 0x41, IME_FONT_MOUNT_POINT, "font.bin",
                                                     &partition_size);
    if (mount == NULL) {
        IME_LOGW(TAG, "no font partition, using the default LVGL font");
        return false;
    }

    size_t big_size = first_font_size(mount->data, mount->size);
    if (big_size == 0) {
        IME_LOGE(TAG, "font partition does not start with a font image");
        ime_vfs_unmount(mount);
        return false;
    }

    /* lv_binfont_create_from_buffer keeps the buffer for glyph loading, so the
     * image is copied out of the memory mapped flash into PSRAM. */
    uint8_t *copy = (uint8_t *)lv_malloc(big_size);
    if (copy == NULL) {
        IME_LOGE(TAG, "out of memory for the big font (%u bytes)", (unsigned)big_size);
        ime_vfs_unmount(mount);
        return false;
    }
    memcpy(copy, mount->data, big_size);
    s_big = lv_binfont_create_from_buffer(copy, (uint32_t)big_size);
    if (s_big == NULL) {
        IME_LOGE(TAG, "lv_binfont_create_from_buffer failed for the big font");
        lv_free(copy);
        ime_vfs_unmount(mount);
        return false;
    }
    IME_LOGI(TAG, "big font: %u bytes loaded from %s", (unsigned)big_size, mount->path);

    if (big_size < mount->size) {
        size_t small_size = mount->size - big_size;
        uint8_t *small_copy = (uint8_t *)lv_malloc(small_size);
        if (small_copy != NULL) {
            memcpy(small_copy, mount->data + big_size, small_size);
            s_small = lv_binfont_create_from_buffer(small_copy, (uint32_t)small_size);
            if (s_small != NULL) {
                IME_LOGI(TAG, "small font: %u bytes loaded", (unsigned)small_size);
            } else {
                lv_free(small_copy);
                IME_LOGW(TAG, "the small font could not be loaded");
            }
        }
    }
#endif

    if (s_big == NULL) {
        IME_LOGW(TAG, "no IME font available, falling back to the default font");
        return false;
    }

    s_prepared = true;
    return true;
}

void ime_font_deinit(void)
{
#if !IME_FONT_USE_EMBEDDED
    if (s_big != NULL) {
        lv_binfont_destroy(s_big);
    }
    if (s_small != NULL) {
        lv_binfont_destroy(s_small);
    }
    ime_vfs_unmount_all();
#endif
    s_big = NULL;
    s_small = NULL;
    s_prepared = false;
}
